export const LangStrings = {
  en: {
    home: "Home",
    categories: "Categories",
    about: "About",
    contact: "Contact",
    language:"Languge",
    search:"Search",
    moto1:"_a minimal store.",
    moto2:"but diverce.",
    latest_arivals:"Last Arivals",
    sales:"on sale",
    view_products:"view products",
    other_products:"other products",
    all_products: "all products",
    hat:"hat",
    t_shirt:"t-shirt",
    shirt:"shirt",
    jacket:"jacket",
    pants:"pants",
    accessory:"accessory",
    sort:"sort by",
    relevence:"relevence",
    sale:"on sales",
    latest:"latest arrivals",
    price_inc:"prcie: low to high",
    price_dec:"prcie: high to low",
    color:"color",
    size:"size",
    read_more:"read more",
    read_less:"read less",
    add_to_cart:"add to cart",
    subtotal:"subtotal",
    tax:"tax",
    tax_cal:"Calculated At Checkout",
    shipping:"shipping",
    free:"free",
    total:"total",
    proceed_checkout:"proceed to checkout",
    name:"name",
    lastname:"lastname",
    phone:"phone",
    address:"address",
    product_name:"product name",
    price:"price",
    amount:"amount",
    submit:"submit",
    return:"return",
    cancel:"cancel",
    continue:"continue",
    asure_q:"Compelete Checkout?",
    cart_table:"Your shopping Cart",
  },
  fa: {
    home: "خانه",
    categories: "دسته بندی ها",
    about: "درباره",
    contact: "تماس",
    language:"زبان",
    search:"جستجو",
    moto1:"فروشگاهی مینیمال",
    moto2:"!اما متنوع",
    latest_arivals:"آخرین محصولات",
    sales:"تخفیف ویژه",
    view_products:"مشاهده محصولات",
    other_products:"محصولات دیگر",
    all_products:"همه محصولات",
    hat:"کلاه",
    t_shirt:"تی شرت",
    shirt:"بلوز",
    jacket:"کت و جاکت",
    pants:"شلوار",
    accessory:"اکسسوری",
    sort:"مرتب سازی",
    relevence:"مرتبط",
    sale:"تخفیف دار",
    latest:"جدید ترین",
    price_inc:"قیمت کم به زیاد",
    price_dec:"قیمت زیاد به کم",
    color:"رنگ",
    size:"اندازه",
    read_more:"مطالعه بیشتر",
    read_less:"مطالعه کمتر",
    add_to_cart:"اضافه به سبد خرید",
    subtotal:"مجموع کالا",
    tax:"مالیات",
    tax_cal:"محاسبه در ادامه",
    shipping:"ارسال",
    free:"رایگان",
    total:"کل",
    proceed_checkout:"ادامه ی پرداخت",
    name:"نام",
    lastname:"نام خانوادگی",
    phone:"شماره تماس",
    address:"نشانی",
    product_name:"نام کالا",
    price:"قیمت",
    amount:"تعداد",
    submit:"ثبت",
    return:"بازگشت",
    cancel:"انصراف",
    continue:"ادامه",
    asure_q:"خرید را کامل میکنید؟",
    cart_table:"سبد خرید شما",
  },
};
